### ISSUE TITLE
パスワード変更不可

### ISSUE THREAD

**Issue by ShoiTakiguchi** [mytheta/SemiRevel#4]
パスワード変更画面で新しいパスワードにしようとしても、パスワードが違うと出ます
<img width="1150" alt="2018-04-11 18 55 48" src="https://user-images.githubusercontent.com/29314206/38609813-117bfe38-3dba-11e8-9bf6-1b4bd443f3ca.png">

ハッシュ化してるからかなあ

**Comment by mytheta** [comment]
hash値で比較してなかった..
直します.

**Comment by mytheta** [comment]
直しました．
本番環境でも確認できましたので．`close`します．
